const SUPABASE_URL = "https://xnuyhifpcwkcplqivmra.supabase.co/rest/v1/";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhudXloaWZwY3drY3BscWl2bXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyMTkyODcsImV4cCI6MjA5NDc5NTI4N30.OIFmYNOAGXMz5o0ckS7NaQNrDkLcZY3EoAPCm012BvI"
